### PR TITLE
Branches lesson

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
I've written a branches lesson which would ideally be used after Conflicts (or possibly after Ignore). As it's a more advanced topic. I've put it as a supplementary lesson for us to discuss and to use to demonstrate extension features of Git.

I note that this will be a controversial topic to present to absolute beginners but it would benefit many users to be exposed to this as they will be joining an existing company or institutional repositories using branches. Thus, following discussions below, this has been move to intermediate material:

https://github.com/swcarpentry/git-novice/issues/306
https://github.com/swcarpentry/git-novice/pull/303

### CODE REVIEW

**Comment by bast** [comment]
Thanks Tom! I first need to follow up on this issue: https://github.com/swcarpentry/bc/issues/929 which I have left abandoned for too long and then I will comment on your changes - I will try to do that tomorrow. Basically I need to figure out whether this repo is the correct base for your changes.

**Comment by bast** [comment]
Hi Tom -  I am sorry - my fork turns out to most probably not to be the right base for your changes. Please see bottom of discussion in https://github.com/swcarpentry/bc/issues/929. Most probably you want to apply your changes to https://github.com/rgaiacs/swc-git-intermediate. I am sorry for the extra work.

**Comment by bast** [comment]
Please let me know once you have applied your changes to the right place - then I will remove this repository to avoid future confusion. Thank you.

**Comment by TomKellyGenetics** [comment]
It looks like the other repo already has a branches lesson. Think this is taken care of for now.

**Comment by bast** [comment]
OK thank you for closing it and sorry for the confusion and the extra work. I have myself forgotten about this issue and have let it there for too long. I will rename this repo to avoid confusion and in some time i will remove it.

**Pull request closed without merging**
